name: CI

on:
  schedule:
    - cron:  '0 0 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    container: python:latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache Python packages
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
          cache: pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pylint
        run: pylint $(pwd)

      - name: Print Python version
        run: python --version

      - name: Run version check
        run: ./check_3rdparty_latest_versions.py
